name: Node.js CI with Artifacts

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npx jest --outputFile=report.html --json

    - name: Upload report artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html
